{
 "title": "Confluent Open Source",
 "description": "Confluent Open Source Grafana Dashboard v5.2.3",
 "tags": [ "5.4.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(zookeeper_initlimit, release)"
   }
  ]
 },
 "panels": [
  { "title": "Confluent Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Aggregated Kafka Broker Pods CPU Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$Release-cp-kafka-(\\\\d+)\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$Release-cp-kafka-(\\\\d+)\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-kafka.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "timeseries",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec{release=~\"$Release\"})",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec{release=~\"$Release\"})",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec{release=~\"$Release\"})",
     "legendFormat": "{{Messages In Per Second}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "timeseries",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequestspersec{release=~\"$Release\"})",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_failedproducerequestspersec{release=~\"$Release\"})",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "timeseries",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequestspersec{release=~\"$Release\"})",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_failedfetchrequestspersec{release=~\"$Release\"})",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "timeseries",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{release=~\"$Release\"}*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "timeseries",
   "description": "Request Handler Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_kafkarequesthandlerpool_requesthandleravgidlepercent{release=~\"$Release\"}*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Confluent Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Number of Connectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_count{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Connector Startup Success Total",
   "type": "stat",
   "description": "The total number of connector starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_startup_success_total{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "stat",
   "description": "The total number of connector starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_startup_failure_total{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_count{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Task Startup Success Total",
   "type": "stat",
   "description": "The total number of task starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_startup_success_total{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "stat",
   "description": "The total number of task starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_startup_failure_total{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connect_1_io_ratio{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Incoming Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connect_1_incoming_byte_rate{release=~\"$Release\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connect_1_network_io_rate{release=~\"$Release\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Confluent Kafka REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number of Kafka REST servers",
   "type": "stat",
   "description": "Number of Kafka REST servers",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_rest_jetty_metrics_connections_active{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Total number of active TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_active{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Open Rate",
   "type": "stat",
   "description": "The average rate per second of opened TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_opened_rate{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "stat",
   "description": "The average rate per second of closed TCP connections.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_closed_rate{release=~\"$Release\"}"
    }
   ]
  },
  {
   "title": "Confluent KSQL Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "KSQL Metrics: Bytes Consumed",
     "type": "timeseries",
     "description": "Total number of bytes consumed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ksql_server_metrics_bytes_consumed_total{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Consumed",
     "type": "timeseries",
     "description": "Messages consumed per second.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ksql_server_metrics_messages_consumed_per_sec{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Produced",
     "type": "timeseries",
     "description": "Messages produced per second.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ksql_server_metrics_messages_produced_per_sec{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Active Queries",
     "type": "timeseries",
     "description": "Number of active queries.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ksql_server_metrics_num_active_queries{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Idle Queries",
     "type": "timeseries",
     "description": "Number of idle queries.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ksql_server_metrics_num_idle_queries{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Persistent Queries",
     "type": "timeseries",
     "description": "Number of persistent queries.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ksql_server_metrics_num_persistent_queries{release=~\"$Release\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "stat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "count(kafka_schema_registry_jetty_metrics_connections_active{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 54 },
     "targets": [
      {
       "expr": "kafka_schema_registry_jetty_metrics_connections_active{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "stat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 54 },
     "targets": [
      {
       "expr": "kafka_schema_registry_jetty_metrics_connections_opened_rate{release=~\"$Release\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "stat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 54 },
     "targets": [
      {
       "expr": "kafka_schema_registry_jetty_metrics_connections_closed_rate{release=~\"$Release\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum Size",
     "type": "stat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "avg(zookeeper_quorumsize{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "stat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 53 },
     "targets": [
      {
       "expr": "sum(zookeeper_numaliveconnections{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "timeseries",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 53 },
     "targets": [
      {
       "expr": "zookeeper_outstandingrequests{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "avg(zookeeper_inmemorydatatree_nodecount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "stat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 57 },
     "targets": [
      {
       "expr": "sum(zookeeper_inmemorydatatree_watchcount{release=~\"$Release\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$Release-cp-zookeeper-(\\\\d+)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod_name=~\"$Release-cp-zookeeper-(\\\\d+)\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-zookeeper.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "timeseries",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "zookeeper_minrequestlatency{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "timeseries",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "targets": [
      {
       "expr": "zookeeper_avgrequestlatency{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "timeseries",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "targets": [
      {
       "expr": "zookeeper_maxrequestlatency{release=~\"$Release\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}