# bootstrap.servers=localhost:9092,localhost:9093,localhost:9094
bootstrap.servers=localhost:9092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
group.id=iot-consumer-group
# auto.offset.reset=latest
auto.offset.reset=earliest
enable.auto.commit=true
auto.commit.interval.ms=1000
# fetch.min.bytes=5000000
fetch.max.wait.ms=5000
# session.timeout.ms=45000
# heartbeat.interval.ms=15000
# max.poll.interval.ms=300000
# request.timeout.ms=60000
# connections.max.idle.ms=540000