# Brokers Kafka (les 3 du cluster)
# bootstrap.servers=localhost:9092,localhost:9093,localhost:9094
bootstrap.servers=localhost:9092

# Sérialisation clé et valeur en String
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Garantie maximale : le leader + tous les ISR doivent confirmer
acks=all

# Nombre de tentatives en cas d'échec
retries=3

# Temps d'attente entre deux tentatives (ms)
retry.backoff.ms=500

# Taille du batch avant envoi (bytes)
batch.size=16384

# Attente max avant d'envoyer un batch incomplet (ms)
linger.ms=5

# Taille totale du buffer mémoire du producer (bytes)
buffer.memory=33554432

# Idempotence : évite les doublons en cas de retry
enable.idempotence=true

# compression
# compression.type=snappy